
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 25;
  public static final int FUNCTION = 29;
  public static final int LBRACKET = 14;
  public static final int OVER = 41;
  public static final int GE = 22;
  public static final int SEMI = 44;
  public static final int LPAREN = 42;
  public static final int REPEAT = 7;
  public static final int ARRAY = 28;
  public static final int MINUS = 39;
  public static final int FOR = 11;
  public static final int WRITE = 10;
  public static final int RPAREN = 43;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int LT = 37;
  public static final int OR = 19;
  public static final int COMMA = 16;
  public static final int CALL = 31;
  public static final int BEGIN = 5;
  public static final int UNTIL = 8;
  public static final int NUM = 34;
  public static final int PLUS = 38;
  public static final int ASSIGN = 35;
  public static final int IF = 2;
  public static final int ID = 33;
  public static final int LE = 23;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int RBRACKET = 15;
  public static final int error = 1;
  public static final int MOD = 17;
  public static final int GLOBAL = 26;
  public static final int EQ = 36;
  public static final int TIMES = 40;
  public static final int COLON = 32;
  public static final int ELSE = 4;
  public static final int READ = 9;
  public static final int TO = 12;
  public static final int THEN = 3;
  public static final int NE = 24;
  public static final int END = 6;
  public static final int GT = 21;
  public static final int VAR = 27;
  public static final int STEP = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "BEGIN",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "FOR",
  "TO",
  "STEP",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "GT",
  "GE",
  "LE",
  "NE",
  "POW",
  "GLOBAL",
  "VAR",
  "ARRAY",
  "FUNCTION",
  "RETURN",
  "CALL",
  "COLON",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI"
  };
}

